### ISSUE TITLE
[FEAT] SVD알고리즘 기반 추천시스템 구축

### ISSUE THREAD

**Issue by Jinlee057** [our-ml-flow/model_pipeline#4]
## Background
- Surprise 라이브러리이용 추천 시스템 구축합니다.
- 여러 알고리즘을 제공 중이나 SVD 기반 알고리즘으로 진행합니다.
- SVD: 유저id, 아이템id, 스코어로 구축 가능하며, 세 데이터 모두 현재 바로 사용 가능
- 일간 거래량 단위로 선정된 고래의 지갑 내의 컬렉션 정보를 이용합니다.
- 주간 거래기준으로 묶은 후 평점대신 사용가능한 스코어링으로 전체 지갑의 NFT과 소유 중인 해당 Collection의 NFT 비율로 계산합니다.
  ex)  : # of Collection's NFT / Total # of NFT in wallet
- 모델 학습은 매주 월요일 아침 9시. 지난 월요일~일요일까지의 데이터를 기준으로 합니다.

## Todo
- [ ] DB서버에서 학습용 데이터로 가져오기
- [ ] 학습 시 Optuna 이용 하이퍼 파라미터 튜닝
- [ ] 구축되어있는 인프라 MLFlow, Minio에 모델 및 메타데이터 저장
- [ ] 학습 스케쥴을 위해 Prefect로 워크플로우 생성
